### ISSUE TITLE
Publish bullseye packages

### ISSUE THREAD

**Issue by pikrzysztof** [kentik/ksynth#2]
We're running a number of bullseye hosts in production, so publishing bullseye packages would be much appreciated.

**Comment by pikrzysztof** [comment]
for example z341.iad1.kentik.com needs it.

**Comment by pikrzysztof** [comment]
Can somebody please have a look at that?

**Comment by wg** [comment]
ksynth 1.4.2 has been released with packages for bullseye, as well as jammy and el/9.
